# Generated by Django 6.0 on 2026-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_namber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
    ]
