# Generated by Django 6.0.2 on 2026-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_namber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='О себе'),
        ),
    ]
