# Generated by Django 6.0 on 2026-01-30 19:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_content_markdawn_alter_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_markdawn',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент'),
        ),
    ]
