# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userpostrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(through='main.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
