# Generated by Django 6.0.2 on 2026-02-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_comment_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
